In [ ]:
Data Science Internship – February 2026  
NLP Assignment 2: Sentiment Analysis  

Name: Hamsini S Y

In [10]:
!pip install nltk

Requirement already satisfied: nltk in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.9.4)
Requirement already satisfied: click in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (2026.3.32)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click->nltk) (0.4.6)

In [15]:
!pip install nltk

import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

nltk.download('stopwords')

Requirement already satisfied: nltk in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.9.4)
Requirement already satisfied: click in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (2026.3.32)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click->nltk) (0.4.6)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hamsini\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
df = pd.read_csv("IMDB Dataset.csv")

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
# Rename for consistency
df.rename(columns={'review': 'text'}, inplace=True)

print(df.columns)

Index(['text', 'sentiment'], dtype='object')

In [18]:
print("Total Samples:", len(df))

print("\nClass Distribution:")
print(df['sentiment'].value_counts())

print("\nSample Text:")
print(df['text'].iloc[0])

Total Samples: 50000

Class Distribution:
sentiment
positive    25000
negative    25000
Name: count, dtype: int64

Sample Text:
One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [19]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess_text(text):
    # Lowercase
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)
    
    # Remove special characters
    text = re.sub(r"[^a-z\s]", "", text)
    
    # Tokenization
    tokens = text.split()
    
    # Remove stopwords + stemming
    tokens = [stemmer.stem(word) for word in tokens if word not in stop_words]
    
    return " ".join(tokens)

In [20]:
df['clean_text'] = df['text'].apply(preprocess_text)

df[['text', 'clean_text']].head()

,text,clean_text
0,One of the other reviewers has mentioned that ...,one review mention watch oz episod youll hook ...
1,A wonderful little production. <br /><br />The...,wonder littl product br br film techniqu unass...
2,I thought this was a wonderful way to spend ti...,thought wonder way spend time hot summer weeke...
3,Basically there's a family where a little boy ...,basic there famili littl boy jake think there ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter mattei love time money visual stun film...

In [21]:
X = df['clean_text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [22]:
bow = CountVectorizer()

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [23]:
tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [24]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Naive Bayes": MultinomialNB(),
    "Decision Tree": DecisionTreeClassifier()
}

results_bow = {}

for name, model in models.items():
    model.fit(X_train_bow, y_train)
    y_pred = model.predict(X_test_bow)

    results_bow[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, average='weighted'),
        "Recall": recall_score(y_test, y_pred, average='weighted'),
        "F1 Score": f1_score(y_test, y_pred, average='weighted')
    }

results_bow

C:\Users\Hamsini\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

{'Logistic Regression': {'Accuracy': 0.8813,
  'Precision': 0.8814256373355264,
  'Recall': 0.8813,
  'F1 Score': 0.881279844502379},
 'Naive Bayes': {'Accuracy': 0.8555,
  'Precision': 0.8559546707273101,
  'Recall': 0.8555,
  'F1 Score': 0.8554770181773022},
 'Decision Tree': {'Accuracy': 0.7263,
  'Precision': 0.7266815948140025,
  'Recall': 0.7263,
  'F1 Score': 0.7262474027461527}}

In [25]:
results_tfidf = {}

for name, model in models.items():
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)

    results_tfidf[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, average='weighted'),
        "Recall": recall_score(y_test, y_pred, average='weighted'),
        "F1 Score": f1_score(y_test, y_pred, average='weighted')
    }

results_tfidf

{'Logistic Regression': {'Accuracy': 0.8895,
  'Precision': 0.8898206602967009,
  'Recall': 0.8895,
  'F1 Score': 0.8894626063164087},
 'Naive Bayes': {'Accuracy': 0.8619,
  'Precision': 0.8622813837559931,
  'Recall': 0.8619,
  'F1 Score': 0.8618835167877104},
 'Decision Tree': {'Accuracy': 0.7211,
  'Precision': 0.7211004439536427,
  'Recall': 0.7211,
  'F1 Score': 0.7211002147657335}}

In [26]:
print("BoW Results:\n")
print(pd.DataFrame(results_bow).T)

print("\nTF-IDF Results:\n")
print(pd.DataFrame(results_tfidf).T)

BoW Results:

                     Accuracy  Precision  Recall  F1 Score
Logistic Regression    0.8813   0.881426  0.8813  0.881280
Naive Bayes            0.8555   0.855955  0.8555  0.855477
Decision Tree          0.7263   0.726682  0.7263  0.726247

TF-IDF Results:

                     Accuracy  Precision  Recall  F1 Score
Logistic Regression    0.8895   0.889821  0.8895  0.889463
Naive Bayes            0.8619   0.862281  0.8619  0.861884
Decision Tree          0.7211   0.721100  0.7211  0.721100

In [ ]:
From the results:

- TF-IDF performed better than Bag of Words because it reduces the impact of frequent words.
- Logistic Regression gave the best performance overall.
- Naive Bayes worked well due to probability-based approach.
- Decision Tree performed lower due to overfitting.

Best Model: Logistic Regression with TF-IDF

Conclusion:
Proper preprocessing and feature engineering significantly improve sentiment analysis performance.